kf_gins_ros2_node:
  ros__parameters:
    imupath: "/home/yang/KF-ROS/ros_ws/src/kf_gins_node/config/dataset/Leador-A15.txt"
    gnsspath: "/home/yang/KF-ROS/ros_ws/src/kf_gins_node/config/dataset/GNSS-RTK.txt"

    outputpath: "/home/yang/KF-ROS/ros_ws/src/kf_gins_node/config/dataset"

    imudatalen: 7
    imudatarate: 200

    starttime: 456250.00439453
    endtime: -1.0

    initpos: [30.4447873701, 114.4718632047, 20.899]
    initvel: [0.0, 0.0, 0.0]
    initatt: [0.0149, -0.0355, 3.24]   # 确认单位正确

    initgyrbias: [0.0, 0.0, 0.0]
    initaccbias: [0.0, 0.0, 0.0]
    initgyrscale: [0.0, 0.0, 0.0]
    initaccscale: [0.0, 0.0, 0.0]

    initposstd: [0.005, 0.004, 0.008]
    initvelstd: [0.003, 0.004, 0.004]
    initattstd: [0.003, 0.003, 0.023]

    imunoise:
      arw: [0.003, 0.003, 0.003]
      vrw: [0.03, 0.03, 0.03]
      gbstd: [0.027, 0.027, 0.027]
      abstd: [0.05, 0.05, 0.05]
      gsstd: [0.0005, 0.0005, 0.0005]
      asstd: [0.0005, 0.0005, 0.0005]
      corrtime: 4.0

      antlever: [0.136, -0.301, -0.184]

    imu_is_increment: true   # 必须改成 false
    imu_units: "si"
